/* this file is generated by version_builder.sh */
/* please do not edit unless you know what you are doing */
#define _GIT_COMMIT_ ("commit 57edf8dff0a272e31580718b8e15174ea145c719 (HEAD, origin/master, origin/HEAD, master)")
#define _GIT_AUTHOR_ ("Author: wolfhead <wolfhead87@gmail.com>")
#define _GIT_DATE_ ("Date:   Mon Dec 28 14:24:34 2015 +0800")
#define GIT_CURRENT_INFO ("commit 57edf8dff0a272e31580718b8e15174ea145c719 (HEAD, origin/master, origin/HEAD, master)\nAuthor: wolfhead <wolfhead87@gmail.com>\nDate:   Mon Dec 28 14:24:34 2015 +0800\n")
